apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gitlabkubtest/myapp:VERSION # Replace with GitLab pipeline variable
        ports:
        - containerPort: 3000 # Updated to match your app
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Updated to match your app
  type: ClusterIP
